name: DAST - ZAP (simple)

on:
  workflow_dispatch:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set TARGET (fallback safe)
        run: |
          if [ -z "${{ secrets.STAGING_URL }}" ]; then
            echo "TARGET=https://example.com" >> $GITHUB_ENV
            echo "No STAGING_URL secret set; using https://example.com"
          else
            echo "TARGET=${{ secrets.STAGING_URL }}" >> $GITHUB_ENV
            echo "Using STAGING_URL=${{ secrets.STAGING_URL }}"
          fi

      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          target: ${{ env.TARGET }}
          fail_action: false
          allow_issue_writing: false
          cmd_options: -d
          artifact_name: zap
