name: SCA - Third-Party Components (Maven)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read

jobs:
  sca_maven:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Run OWASP Dependency-Check (Maven plugin)
        run: |
          mvn -B org.owasp:dependency-check-maven:check \
            -Dformat=HTML,JSON \
            -DoutputDirectory=target/dependency-check-report \
            -DfailOnCVSS=0
          continue-on-error: true

      - name: Upload Dependency-Check reports
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: |
            target/dependency-check-report/dependency-check-report.html
            target/dependency-check-report/dependency-check-report.json
