name: SAST - Semgrep Code Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read
  security-events: write   # necessário para subir o SARIF
  actions: read

jobs:
  semgrep:
    runs-on: ubuntu-latest
    name: Run Semgrep scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Executa Semgrep com regras focadas em segurança
      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: |
            p/owasp-top-ten
            p/security-audit
            p/secrets
          generateSarif: true          # garante saída em SARIF
          sarifFile: semgrep.sarif     # nome do arquivo gerado

      # Publica o relatório na aba Security > Code scanning
      - name: Upload SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif

      # (Opcional) Salva o relatório como artefato do job
      - name: Upload Semgrep report artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep.sarif
